server.port=8085
db.url=jdbc:mysql://localhost:3306/intellibank_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=12345
db.pool.maxSize=15
db.pool.minIdle=5
jwt.secret=c3VwZXJfc2VjdXJlX2p3dF9zZWNyZXRfa2V5X2Zvcl9pbnRlbGxpYmFua19iMnJfYXBwbGljYXRpb25fMjAyNl9zZWN1cmU=
jwt.expiry.minutes=120
login.max.attempts=5
login.lockout.minutes=15
